### ISSUE TITLE
please share downloaded instructions for pygosemsim

### ISSUE THREAD

**Issue by AhmedArslan** [mojaie/pygosemsim#2]
please share downloaded instruction for pygosemsim, I tried with pip3 but it didn't work:

$pip3 install please pygosemsim
Collecting please
  Using cached https://files.pythonhosted.org/packages/3a/05/8884f25a2ac3492156ae0c0a9224200a985dc4fa7a7363e2e12a2e9f31cb/PLEASE-0.9.8-py3-none-any.whl
Collecting pygosemsim
  Could not find a version that satisfies the requirement pygosemsim (from versions: )
No matching distribution found for pygosemsim

**Comment by mojaie** [comment]
Unfortunately this package is not registered to PyPI yet.

try this:
```pip3 install git+https://github.com/mojaie/pygosemsim.git```

Note that this project is almost inactive.
