### ISSUE TITLE
pygosemsim.exception.PGSSInvalidOperation: 'Pre-calculated lower bounds' is required.

### ISSUE THREAD

**Issue by AhmedArslan** [mojaie/pygosemsim#3]
similarity.resnik(G, "GO:0004340", "GO:0019158")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Downloads/pygosemsim-master/pygosemsim/similarity.py", line 89, in resnik
    mica = lowest_common_ancestor(G, term1, term2)
  File "/Users/Downloads/pygosemsim-master/pygosemsim/similarity.py", line 58, in lowest_common_ancestor
    G.require("Pre-calculated lower bounds")
  File "/Users/Downloads/pygosemsim-master/pygosemsim/graph.py", line 38, in require
    "'{}' is required.".format(desc))
pygosemsim.exception.PGSSInvalidOperation: 'Pre-calculated lower bounds' is required.

**Comment by mojaie** [comment]
see the instruction
https://github.com/mojaie/pygosemsim/blob/master/README.md#go-term-semantic-similarity
`precalc_lower_bounds` is necessary before you call `resnik`

**Comment by AhmedArslan** [comment]
Please:
graph.precalc_lower_bounds(G)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pygosemsim.graph' has no attribute 'precalc_lower_bounds'

**Comment by mojaie** [comment]
Oh... The instruction is wrong.
try:
```
similarity.precalc_lower_bounds(G)
```

Thank you very much for catching it.

**Comment by AhmedArslan** [comment]
Welcome, can I implement similarity() for a (long) list of GO-terms to analyze functional similarity instead of two GO-terms? How? 
As below:
similarity.resnik(G, "GO:0004340", "GO:0019158", ...., n)

**Comment by mojaie** [comment]
Similarity can be defined only between two items.
If you want to compare a list of terms with a reference term, use Python built-in iterator.
```py
import functools
resnikfunc = functools.partial(similarity.resnik, G, ref_term)
for s in map(resnikfunc, terms)
    print(s)
```

Or, pairwise computation can be done by using `itertools.combination` 
```py
import itertools
for a, b in itertools.combination(terms)
    print("{} {} : {}".format(a, b,  resnikfunc(similarity.resnik, a, b))
```

**Comment by mojaie** [comment]
The second example code was corrected as below
```
import itertools
for a, b in itertools.combination(terms)
    print("{} {} : {}".format(a, b,  similarity.resnik(a, b)))
```
